# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 3.23

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = "C:\Program Files\CMake\bin\cmake.exe"

# The command to remove a file.
RM = "C:\Program Files\CMake\bin\cmake.exe" -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = C:\Users\myaka\Documents\Github\Fastboi

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = C:\Users\myaka\Documents\Github\Fastboi

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	"C:\Program Files\CMake\bin\cmake-gui.exe" -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	"C:\Program Files\CMake\bin\cmake.exe" --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start C:\Users\myaka\Documents\Github\Fastboi\CMakeFiles C:\Users\myaka\Documents\Github\Fastboi\\CMakeFiles\progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start C:\Users\myaka\Documents\Github\Fastboi\CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -P C:\Users\myaka\Documents\Github\Fastboi\CMakeFiles\VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named adventure

# Build rule for target.
adventure: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 adventure
.PHONY : adventure

# fast build rule for target.
adventure/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\adventure.dir\build.make CMakeFiles/adventure.dir/build
.PHONY : adventure/fast

deps/soloud/src/audiosource/wav/dr_impl.obj: deps/soloud/src/audiosource/wav/dr_impl.cpp.obj
.PHONY : deps/soloud/src/audiosource/wav/dr_impl.obj

# target to build an object file
deps/soloud/src/audiosource/wav/dr_impl.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\adventure.dir\build.make CMakeFiles/adventure.dir/deps/soloud/src/audiosource/wav/dr_impl.cpp.obj
.PHONY : deps/soloud/src/audiosource/wav/dr_impl.cpp.obj

deps/soloud/src/audiosource/wav/dr_impl.i: deps/soloud/src/audiosource/wav/dr_impl.cpp.i
.PHONY : deps/soloud/src/audiosource/wav/dr_impl.i

# target to preprocess a source file
deps/soloud/src/audiosource/wav/dr_impl.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\adventure.dir\build.make CMakeFiles/adventure.dir/deps/soloud/src/audiosource/wav/dr_impl.cpp.i
.PHONY : deps/soloud/src/audiosource/wav/dr_impl.cpp.i

deps/soloud/src/audiosource/wav/dr_impl.s: deps/soloud/src/audiosource/wav/dr_impl.cpp.s
.PHONY : deps/soloud/src/audiosource/wav/dr_impl.s

# target to generate assembly for a file
deps/soloud/src/audiosource/wav/dr_impl.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\adventure.dir\build.make CMakeFiles/adventure.dir/deps/soloud/src/audiosource/wav/dr_impl.cpp.s
.PHONY : deps/soloud/src/audiosource/wav/dr_impl.cpp.s

deps/soloud/src/audiosource/wav/soloud_wav.obj: deps/soloud/src/audiosource/wav/soloud_wav.cpp.obj
.PHONY : deps/soloud/src/audiosource/wav/soloud_wav.obj

# target to build an object file
deps/soloud/src/audiosource/wav/soloud_wav.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\adventure.dir\build.make CMakeFiles/adventure.dir/deps/soloud/src/audiosource/wav/soloud_wav.cpp.obj
.PHONY : deps/soloud/src/audiosource/wav/soloud_wav.cpp.obj

deps/soloud/src/audiosource/wav/soloud_wav.i: deps/soloud/src/audiosource/wav/soloud_wav.cpp.i
.PHONY : deps/soloud/src/audiosource/wav/soloud_wav.i

# target to preprocess a source file
deps/soloud/src/audiosource/wav/soloud_wav.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\adventure.dir\build.make CMakeFiles/adventure.dir/deps/soloud/src/audiosource/wav/soloud_wav.cpp.i
.PHONY : deps/soloud/src/audiosource/wav/soloud_wav.cpp.i

deps/soloud/src/audiosource/wav/soloud_wav.s: deps/soloud/src/audiosource/wav/soloud_wav.cpp.s
.PHONY : deps/soloud/src/audiosource/wav/soloud_wav.s

# target to generate assembly for a file
deps/soloud/src/audiosource/wav/soloud_wav.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\adventure.dir\build.make CMakeFiles/adventure.dir/deps/soloud/src/audiosource/wav/soloud_wav.cpp.s
.PHONY : deps/soloud/src/audiosource/wav/soloud_wav.cpp.s

deps/soloud/src/audiosource/wav/soloud_wavstream.obj: deps/soloud/src/audiosource/wav/soloud_wavstream.cpp.obj
.PHONY : deps/soloud/src/audiosource/wav/soloud_wavstream.obj

# target to build an object file
deps/soloud/src/audiosource/wav/soloud_wavstream.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\adventure.dir\build.make CMakeFiles/adventure.dir/deps/soloud/src/audiosource/wav/soloud_wavstream.cpp.obj
.PHONY : deps/soloud/src/audiosource/wav/soloud_wavstream.cpp.obj

deps/soloud/src/audiosource/wav/soloud_wavstream.i: deps/soloud/src/audiosource/wav/soloud_wavstream.cpp.i
.PHONY : deps/soloud/src/audiosource/wav/soloud_wavstream.i

# target to preprocess a source file
deps/soloud/src/audiosource/wav/soloud_wavstream.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\adventure.dir\build.make CMakeFiles/adventure.dir/deps/soloud/src/audiosource/wav/soloud_wavstream.cpp.i
.PHONY : deps/soloud/src/audiosource/wav/soloud_wavstream.cpp.i

deps/soloud/src/audiosource/wav/soloud_wavstream.s: deps/soloud/src/audiosource/wav/soloud_wavstream.cpp.s
.PHONY : deps/soloud/src/audiosource/wav/soloud_wavstream.s

# target to generate assembly for a file
deps/soloud/src/audiosource/wav/soloud_wavstream.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\adventure.dir\build.make CMakeFiles/adventure.dir/deps/soloud/src/audiosource/wav/soloud_wavstream.cpp.s
.PHONY : deps/soloud/src/audiosource/wav/soloud_wavstream.cpp.s

deps/soloud/src/audiosource/wav/stb_vorbis.obj: deps/soloud/src/audiosource/wav/stb_vorbis.c.obj
.PHONY : deps/soloud/src/audiosource/wav/stb_vorbis.obj

# target to build an object file
deps/soloud/src/audiosource/wav/stb_vorbis.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\adventure.dir\build.make CMakeFiles/adventure.dir/deps/soloud/src/audiosource/wav/stb_vorbis.c.obj
.PHONY : deps/soloud/src/audiosource/wav/stb_vorbis.c.obj

deps/soloud/src/audiosource/wav/stb_vorbis.i: deps/soloud/src/audiosource/wav/stb_vorbis.c.i
.PHONY : deps/soloud/src/audiosource/wav/stb_vorbis.i

# target to preprocess a source file
deps/soloud/src/audiosource/wav/stb_vorbis.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\adventure.dir\build.make CMakeFiles/adventure.dir/deps/soloud/src/audiosource/wav/stb_vorbis.c.i
.PHONY : deps/soloud/src/audiosource/wav/stb_vorbis.c.i

deps/soloud/src/audiosource/wav/stb_vorbis.s: deps/soloud/src/audiosource/wav/stb_vorbis.c.s
.PHONY : deps/soloud/src/audiosource/wav/stb_vorbis.s

# target to generate assembly for a file
deps/soloud/src/audiosource/wav/stb_vorbis.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\adventure.dir\build.make CMakeFiles/adventure.dir/deps/soloud/src/audiosource/wav/stb_vorbis.c.s
.PHONY : deps/soloud/src/audiosource/wav/stb_vorbis.c.s

deps/soloud/src/backend/sdl2_static/soloud_sdl2_static.obj: deps/soloud/src/backend/sdl2_static/soloud_sdl2_static.cpp.obj
.PHONY : deps/soloud/src/backend/sdl2_static/soloud_sdl2_static.obj

# target to build an object file
deps/soloud/src/backend/sdl2_static/soloud_sdl2_static.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\adventure.dir\build.make CMakeFiles/adventure.dir/deps/soloud/src/backend/sdl2_static/soloud_sdl2_static.cpp.obj
.PHONY : deps/soloud/src/backend/sdl2_static/soloud_sdl2_static.cpp.obj

deps/soloud/src/backend/sdl2_static/soloud_sdl2_static.i: deps/soloud/src/backend/sdl2_static/soloud_sdl2_static.cpp.i
.PHONY : deps/soloud/src/backend/sdl2_static/soloud_sdl2_static.i

# target to preprocess a source file
deps/soloud/src/backend/sdl2_static/soloud_sdl2_static.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\adventure.dir\build.make CMakeFiles/adventure.dir/deps/soloud/src/backend/sdl2_static/soloud_sdl2_static.cpp.i
.PHONY : deps/soloud/src/backend/sdl2_static/soloud_sdl2_static.cpp.i

deps/soloud/src/backend/sdl2_static/soloud_sdl2_static.s: deps/soloud/src/backend/sdl2_static/soloud_sdl2_static.cpp.s
.PHONY : deps/soloud/src/backend/sdl2_static/soloud_sdl2_static.s

# target to generate assembly for a file
deps/soloud/src/backend/sdl2_static/soloud_sdl2_static.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\adventure.dir\build.make CMakeFiles/adventure.dir/deps/soloud/src/backend/sdl2_static/soloud_sdl2_static.cpp.s
.PHONY : deps/soloud/src/backend/sdl2_static/soloud_sdl2_static.cpp.s

deps/soloud/src/core/soloud.obj: deps/soloud/src/core/soloud.cpp.obj
.PHONY : deps/soloud/src/core/soloud.obj

# target to build an object file
deps/soloud/src/core/soloud.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\adventure.dir\build.make CMakeFiles/adventure.dir/deps/soloud/src/core/soloud.cpp.obj
.PHONY : deps/soloud/src/core/soloud.cpp.obj

deps/soloud/src/core/soloud.i: deps/soloud/src/core/soloud.cpp.i
.PHONY : deps/soloud/src/core/soloud.i

# target to preprocess a source file
deps/soloud/src/core/soloud.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\adventure.dir\build.make CMakeFiles/adventure.dir/deps/soloud/src/core/soloud.cpp.i
.PHONY : deps/soloud/src/core/soloud.cpp.i

deps/soloud/src/core/soloud.s: deps/soloud/src/core/soloud.cpp.s
.PHONY : deps/soloud/src/core/soloud.s

# target to generate assembly for a file
deps/soloud/src/core/soloud.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\adventure.dir\build.make CMakeFiles/adventure.dir/deps/soloud/src/core/soloud.cpp.s
.PHONY : deps/soloud/src/core/soloud.cpp.s

deps/soloud/src/core/soloud_audiosource.obj: deps/soloud/src/core/soloud_audiosource.cpp.obj
.PHONY : deps/soloud/src/core/soloud_audiosource.obj

# target to build an object file
deps/soloud/src/core/soloud_audiosource.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\adventure.dir\build.make CMakeFiles/adventure.dir/deps/soloud/src/core/soloud_audiosource.cpp.obj
.PHONY : deps/soloud/src/core/soloud_audiosource.cpp.obj

deps/soloud/src/core/soloud_audiosource.i: deps/soloud/src/core/soloud_audiosource.cpp.i
.PHONY : deps/soloud/src/core/soloud_audiosource.i

# target to preprocess a source file
deps/soloud/src/core/soloud_audiosource.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\adventure.dir\build.make CMakeFiles/adventure.dir/deps/soloud/src/core/soloud_audiosource.cpp.i
.PHONY : deps/soloud/src/core/soloud_audiosource.cpp.i

deps/soloud/src/core/soloud_audiosource.s: deps/soloud/src/core/soloud_audiosource.cpp.s
.PHONY : deps/soloud/src/core/soloud_audiosource.s

# target to generate assembly for a file
deps/soloud/src/core/soloud_audiosource.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\adventure.dir\build.make CMakeFiles/adventure.dir/deps/soloud/src/core/soloud_audiosource.cpp.s
.PHONY : deps/soloud/src/core/soloud_audiosource.cpp.s

deps/soloud/src/core/soloud_bus.obj: deps/soloud/src/core/soloud_bus.cpp.obj
.PHONY : deps/soloud/src/core/soloud_bus.obj

# target to build an object file
deps/soloud/src/core/soloud_bus.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\adventure.dir\build.make CMakeFiles/adventure.dir/deps/soloud/src/core/soloud_bus.cpp.obj
.PHONY : deps/soloud/src/core/soloud_bus.cpp.obj

deps/soloud/src/core/soloud_bus.i: deps/soloud/src/core/soloud_bus.cpp.i
.PHONY : deps/soloud/src/core/soloud_bus.i

# target to preprocess a source file
deps/soloud/src/core/soloud_bus.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\adventure.dir\build.make CMakeFiles/adventure.dir/deps/soloud/src/core/soloud_bus.cpp.i
.PHONY : deps/soloud/src/core/soloud_bus.cpp.i

deps/soloud/src/core/soloud_bus.s: deps/soloud/src/core/soloud_bus.cpp.s
.PHONY : deps/soloud/src/core/soloud_bus.s

# target to generate assembly for a file
deps/soloud/src/core/soloud_bus.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\adventure.dir\build.make CMakeFiles/adventure.dir/deps/soloud/src/core/soloud_bus.cpp.s
.PHONY : deps/soloud/src/core/soloud_bus.cpp.s

deps/soloud/src/core/soloud_core_3d.obj: deps/soloud/src/core/soloud_core_3d.cpp.obj
.PHONY : deps/soloud/src/core/soloud_core_3d.obj

# target to build an object file
deps/soloud/src/core/soloud_core_3d.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\adventure.dir\build.make CMakeFiles/adventure.dir/deps/soloud/src/core/soloud_core_3d.cpp.obj
.PHONY : deps/soloud/src/core/soloud_core_3d.cpp.obj

deps/soloud/src/core/soloud_core_3d.i: deps/soloud/src/core/soloud_core_3d.cpp.i
.PHONY : deps/soloud/src/core/soloud_core_3d.i

# target to preprocess a source file
deps/soloud/src/core/soloud_core_3d.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\adventure.dir\build.make CMakeFiles/adventure.dir/deps/soloud/src/core/soloud_core_3d.cpp.i
.PHONY : deps/soloud/src/core/soloud_core_3d.cpp.i

deps/soloud/src/core/soloud_core_3d.s: deps/soloud/src/core/soloud_core_3d.cpp.s
.PHONY : deps/soloud/src/core/soloud_core_3d.s

# target to generate assembly for a file
deps/soloud/src/core/soloud_core_3d.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\adventure.dir\build.make CMakeFiles/adventure.dir/deps/soloud/src/core/soloud_core_3d.cpp.s
.PHONY : deps/soloud/src/core/soloud_core_3d.cpp.s

deps/soloud/src/core/soloud_core_basicops.obj: deps/soloud/src/core/soloud_core_basicops.cpp.obj
.PHONY : deps/soloud/src/core/soloud_core_basicops.obj

# target to build an object file
deps/soloud/src/core/soloud_core_basicops.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\adventure.dir\build.make CMakeFiles/adventure.dir/deps/soloud/src/core/soloud_core_basicops.cpp.obj
.PHONY : deps/soloud/src/core/soloud_core_basicops.cpp.obj

deps/soloud/src/core/soloud_core_basicops.i: deps/soloud/src/core/soloud_core_basicops.cpp.i
.PHONY : deps/soloud/src/core/soloud_core_basicops.i

# target to preprocess a source file
deps/soloud/src/core/soloud_core_basicops.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\adventure.dir\build.make CMakeFiles/adventure.dir/deps/soloud/src/core/soloud_core_basicops.cpp.i
.PHONY : deps/soloud/src/core/soloud_core_basicops.cpp.i

deps/soloud/src/core/soloud_core_basicops.s: deps/soloud/src/core/soloud_core_basicops.cpp.s
.PHONY : deps/soloud/src/core/soloud_core_basicops.s

# target to generate assembly for a file
deps/soloud/src/core/soloud_core_basicops.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\adventure.dir\build.make CMakeFiles/adventure.dir/deps/soloud/src/core/soloud_core_basicops.cpp.s
.PHONY : deps/soloud/src/core/soloud_core_basicops.cpp.s

deps/soloud/src/core/soloud_core_faderops.obj: deps/soloud/src/core/soloud_core_faderops.cpp.obj
.PHONY : deps/soloud/src/core/soloud_core_faderops.obj

# target to build an object file
deps/soloud/src/core/soloud_core_faderops.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\adventure.dir\build.make CMakeFiles/adventure.dir/deps/soloud/src/core/soloud_core_faderops.cpp.obj
.PHONY : deps/soloud/src/core/soloud_core_faderops.cpp.obj

deps/soloud/src/core/soloud_core_faderops.i: deps/soloud/src/core/soloud_core_faderops.cpp.i
.PHONY : deps/soloud/src/core/soloud_core_faderops.i

# target to preprocess a source file
deps/soloud/src/core/soloud_core_faderops.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\adventure.dir\build.make CMakeFiles/adventure.dir/deps/soloud/src/core/soloud_core_faderops.cpp.i
.PHONY : deps/soloud/src/core/soloud_core_faderops.cpp.i

deps/soloud/src/core/soloud_core_faderops.s: deps/soloud/src/core/soloud_core_faderops.cpp.s
.PHONY : deps/soloud/src/core/soloud_core_faderops.s

# target to generate assembly for a file
deps/soloud/src/core/soloud_core_faderops.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\adventure.dir\build.make CMakeFiles/adventure.dir/deps/soloud/src/core/soloud_core_faderops.cpp.s
.PHONY : deps/soloud/src/core/soloud_core_faderops.cpp.s

deps/soloud/src/core/soloud_core_filterops.obj: deps/soloud/src/core/soloud_core_filterops.cpp.obj
.PHONY : deps/soloud/src/core/soloud_core_filterops.obj

# target to build an object file
deps/soloud/src/core/soloud_core_filterops.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\adventure.dir\build.make CMakeFiles/adventure.dir/deps/soloud/src/core/soloud_core_filterops.cpp.obj
.PHONY : deps/soloud/src/core/soloud_core_filterops.cpp.obj

deps/soloud/src/core/soloud_core_filterops.i: deps/soloud/src/core/soloud_core_filterops.cpp.i
.PHONY : deps/soloud/src/core/soloud_core_filterops.i

# target to preprocess a source file
deps/soloud/src/core/soloud_core_filterops.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\adventure.dir\build.make CMakeFiles/adventure.dir/deps/soloud/src/core/soloud_core_filterops.cpp.i
.PHONY : deps/soloud/src/core/soloud_core_filterops.cpp.i

deps/soloud/src/core/soloud_core_filterops.s: deps/soloud/src/core/soloud_core_filterops.cpp.s
.PHONY : deps/soloud/src/core/soloud_core_filterops.s

# target to generate assembly for a file
deps/soloud/src/core/soloud_core_filterops.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\adventure.dir\build.make CMakeFiles/adventure.dir/deps/soloud/src/core/soloud_core_filterops.cpp.s
.PHONY : deps/soloud/src/core/soloud_core_filterops.cpp.s

deps/soloud/src/core/soloud_core_getters.obj: deps/soloud/src/core/soloud_core_getters.cpp.obj
.PHONY : deps/soloud/src/core/soloud_core_getters.obj

# target to build an object file
deps/soloud/src/core/soloud_core_getters.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\adventure.dir\build.make CMakeFiles/adventure.dir/deps/soloud/src/core/soloud_core_getters.cpp.obj
.PHONY : deps/soloud/src/core/soloud_core_getters.cpp.obj

deps/soloud/src/core/soloud_core_getters.i: deps/soloud/src/core/soloud_core_getters.cpp.i
.PHONY : deps/soloud/src/core/soloud_core_getters.i

# target to preprocess a source file
deps/soloud/src/core/soloud_core_getters.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\adventure.dir\build.make CMakeFiles/adventure.dir/deps/soloud/src/core/soloud_core_getters.cpp.i
.PHONY : deps/soloud/src/core/soloud_core_getters.cpp.i

deps/soloud/src/core/soloud_core_getters.s: deps/soloud/src/core/soloud_core_getters.cpp.s
.PHONY : deps/soloud/src/core/soloud_core_getters.s

# target to generate assembly for a file
deps/soloud/src/core/soloud_core_getters.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\adventure.dir\build.make CMakeFiles/adventure.dir/deps/soloud/src/core/soloud_core_getters.cpp.s
.PHONY : deps/soloud/src/core/soloud_core_getters.cpp.s

deps/soloud/src/core/soloud_core_setters.obj: deps/soloud/src/core/soloud_core_setters.cpp.obj
.PHONY : deps/soloud/src/core/soloud_core_setters.obj

# target to build an object file
deps/soloud/src/core/soloud_core_setters.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\adventure.dir\build.make CMakeFiles/adventure.dir/deps/soloud/src/core/soloud_core_setters.cpp.obj
.PHONY : deps/soloud/src/core/soloud_core_setters.cpp.obj

deps/soloud/src/core/soloud_core_setters.i: deps/soloud/src/core/soloud_core_setters.cpp.i
.PHONY : deps/soloud/src/core/soloud_core_setters.i

# target to preprocess a source file
deps/soloud/src/core/soloud_core_setters.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\adventure.dir\build.make CMakeFiles/adventure.dir/deps/soloud/src/core/soloud_core_setters.cpp.i
.PHONY : deps/soloud/src/core/soloud_core_setters.cpp.i

deps/soloud/src/core/soloud_core_setters.s: deps/soloud/src/core/soloud_core_setters.cpp.s
.PHONY : deps/soloud/src/core/soloud_core_setters.s

# target to generate assembly for a file
deps/soloud/src/core/soloud_core_setters.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\adventure.dir\build.make CMakeFiles/adventure.dir/deps/soloud/src/core/soloud_core_setters.cpp.s
.PHONY : deps/soloud/src/core/soloud_core_setters.cpp.s

deps/soloud/src/core/soloud_core_voicegroup.obj: deps/soloud/src/core/soloud_core_voicegroup.cpp.obj
.PHONY : deps/soloud/src/core/soloud_core_voicegroup.obj

# target to build an object file
deps/soloud/src/core/soloud_core_voicegroup.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\adventure.dir\build.make CMakeFiles/adventure.dir/deps/soloud/src/core/soloud_core_voicegroup.cpp.obj
.PHONY : deps/soloud/src/core/soloud_core_voicegroup.cpp.obj

deps/soloud/src/core/soloud_core_voicegroup.i: deps/soloud/src/core/soloud_core_voicegroup.cpp.i
.PHONY : deps/soloud/src/core/soloud_core_voicegroup.i

# target to preprocess a source file
deps/soloud/src/core/soloud_core_voicegroup.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\adventure.dir\build.make CMakeFiles/adventure.dir/deps/soloud/src/core/soloud_core_voicegroup.cpp.i
.PHONY : deps/soloud/src/core/soloud_core_voicegroup.cpp.i

deps/soloud/src/core/soloud_core_voicegroup.s: deps/soloud/src/core/soloud_core_voicegroup.cpp.s
.PHONY : deps/soloud/src/core/soloud_core_voicegroup.s

# target to generate assembly for a file
deps/soloud/src/core/soloud_core_voicegroup.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\adventure.dir\build.make CMakeFiles/adventure.dir/deps/soloud/src/core/soloud_core_voicegroup.cpp.s
.PHONY : deps/soloud/src/core/soloud_core_voicegroup.cpp.s

deps/soloud/src/core/soloud_core_voiceops.obj: deps/soloud/src/core/soloud_core_voiceops.cpp.obj
.PHONY : deps/soloud/src/core/soloud_core_voiceops.obj

# target to build an object file
deps/soloud/src/core/soloud_core_voiceops.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\adventure.dir\build.make CMakeFiles/adventure.dir/deps/soloud/src/core/soloud_core_voiceops.cpp.obj
.PHONY : deps/soloud/src/core/soloud_core_voiceops.cpp.obj

deps/soloud/src/core/soloud_core_voiceops.i: deps/soloud/src/core/soloud_core_voiceops.cpp.i
.PHONY : deps/soloud/src/core/soloud_core_voiceops.i

# target to preprocess a source file
deps/soloud/src/core/soloud_core_voiceops.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\adventure.dir\build.make CMakeFiles/adventure.dir/deps/soloud/src/core/soloud_core_voiceops.cpp.i
.PHONY : deps/soloud/src/core/soloud_core_voiceops.cpp.i

deps/soloud/src/core/soloud_core_voiceops.s: deps/soloud/src/core/soloud_core_voiceops.cpp.s
.PHONY : deps/soloud/src/core/soloud_core_voiceops.s

# target to generate assembly for a file
deps/soloud/src/core/soloud_core_voiceops.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\adventure.dir\build.make CMakeFiles/adventure.dir/deps/soloud/src/core/soloud_core_voiceops.cpp.s
.PHONY : deps/soloud/src/core/soloud_core_voiceops.cpp.s

deps/soloud/src/core/soloud_fader.obj: deps/soloud/src/core/soloud_fader.cpp.obj
.PHONY : deps/soloud/src/core/soloud_fader.obj

# target to build an object file
deps/soloud/src/core/soloud_fader.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\adventure.dir\build.make CMakeFiles/adventure.dir/deps/soloud/src/core/soloud_fader.cpp.obj
.PHONY : deps/soloud/src/core/soloud_fader.cpp.obj

deps/soloud/src/core/soloud_fader.i: deps/soloud/src/core/soloud_fader.cpp.i
.PHONY : deps/soloud/src/core/soloud_fader.i

# target to preprocess a source file
deps/soloud/src/core/soloud_fader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\adventure.dir\build.make CMakeFiles/adventure.dir/deps/soloud/src/core/soloud_fader.cpp.i
.PHONY : deps/soloud/src/core/soloud_fader.cpp.i

deps/soloud/src/core/soloud_fader.s: deps/soloud/src/core/soloud_fader.cpp.s
.PHONY : deps/soloud/src/core/soloud_fader.s

# target to generate assembly for a file
deps/soloud/src/core/soloud_fader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\adventure.dir\build.make CMakeFiles/adventure.dir/deps/soloud/src/core/soloud_fader.cpp.s
.PHONY : deps/soloud/src/core/soloud_fader.cpp.s

deps/soloud/src/core/soloud_fft.obj: deps/soloud/src/core/soloud_fft.cpp.obj
.PHONY : deps/soloud/src/core/soloud_fft.obj

# target to build an object file
deps/soloud/src/core/soloud_fft.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\adventure.dir\build.make CMakeFiles/adventure.dir/deps/soloud/src/core/soloud_fft.cpp.obj
.PHONY : deps/soloud/src/core/soloud_fft.cpp.obj

deps/soloud/src/core/soloud_fft.i: deps/soloud/src/core/soloud_fft.cpp.i
.PHONY : deps/soloud/src/core/soloud_fft.i

# target to preprocess a source file
deps/soloud/src/core/soloud_fft.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\adventure.dir\build.make CMakeFiles/adventure.dir/deps/soloud/src/core/soloud_fft.cpp.i
.PHONY : deps/soloud/src/core/soloud_fft.cpp.i

deps/soloud/src/core/soloud_fft.s: deps/soloud/src/core/soloud_fft.cpp.s
.PHONY : deps/soloud/src/core/soloud_fft.s

# target to generate assembly for a file
deps/soloud/src/core/soloud_fft.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\adventure.dir\build.make CMakeFiles/adventure.dir/deps/soloud/src/core/soloud_fft.cpp.s
.PHONY : deps/soloud/src/core/soloud_fft.cpp.s

deps/soloud/src/core/soloud_fft_lut.obj: deps/soloud/src/core/soloud_fft_lut.cpp.obj
.PHONY : deps/soloud/src/core/soloud_fft_lut.obj

# target to build an object file
deps/soloud/src/core/soloud_fft_lut.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\adventure.dir\build.make CMakeFiles/adventure.dir/deps/soloud/src/core/soloud_fft_lut.cpp.obj
.PHONY : deps/soloud/src/core/soloud_fft_lut.cpp.obj

deps/soloud/src/core/soloud_fft_lut.i: deps/soloud/src/core/soloud_fft_lut.cpp.i
.PHONY : deps/soloud/src/core/soloud_fft_lut.i

# target to preprocess a source file
deps/soloud/src/core/soloud_fft_lut.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\adventure.dir\build.make CMakeFiles/adventure.dir/deps/soloud/src/core/soloud_fft_lut.cpp.i
.PHONY : deps/soloud/src/core/soloud_fft_lut.cpp.i

deps/soloud/src/core/soloud_fft_lut.s: deps/soloud/src/core/soloud_fft_lut.cpp.s
.PHONY : deps/soloud/src/core/soloud_fft_lut.s

# target to generate assembly for a file
deps/soloud/src/core/soloud_fft_lut.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\adventure.dir\build.make CMakeFiles/adventure.dir/deps/soloud/src/core/soloud_fft_lut.cpp.s
.PHONY : deps/soloud/src/core/soloud_fft_lut.cpp.s

deps/soloud/src/core/soloud_file.obj: deps/soloud/src/core/soloud_file.cpp.obj
.PHONY : deps/soloud/src/core/soloud_file.obj

# target to build an object file
deps/soloud/src/core/soloud_file.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\adventure.dir\build.make CMakeFiles/adventure.dir/deps/soloud/src/core/soloud_file.cpp.obj
.PHONY : deps/soloud/src/core/soloud_file.cpp.obj

deps/soloud/src/core/soloud_file.i: deps/soloud/src/core/soloud_file.cpp.i
.PHONY : deps/soloud/src/core/soloud_file.i

# target to preprocess a source file
deps/soloud/src/core/soloud_file.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\adventure.dir\build.make CMakeFiles/adventure.dir/deps/soloud/src/core/soloud_file.cpp.i
.PHONY : deps/soloud/src/core/soloud_file.cpp.i

deps/soloud/src/core/soloud_file.s: deps/soloud/src/core/soloud_file.cpp.s
.PHONY : deps/soloud/src/core/soloud_file.s

# target to generate assembly for a file
deps/soloud/src/core/soloud_file.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\adventure.dir\build.make CMakeFiles/adventure.dir/deps/soloud/src/core/soloud_file.cpp.s
.PHONY : deps/soloud/src/core/soloud_file.cpp.s

deps/soloud/src/core/soloud_filter.obj: deps/soloud/src/core/soloud_filter.cpp.obj
.PHONY : deps/soloud/src/core/soloud_filter.obj

# target to build an object file
deps/soloud/src/core/soloud_filter.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\adventure.dir\build.make CMakeFiles/adventure.dir/deps/soloud/src/core/soloud_filter.cpp.obj
.PHONY : deps/soloud/src/core/soloud_filter.cpp.obj

deps/soloud/src/core/soloud_filter.i: deps/soloud/src/core/soloud_filter.cpp.i
.PHONY : deps/soloud/src/core/soloud_filter.i

# target to preprocess a source file
deps/soloud/src/core/soloud_filter.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\adventure.dir\build.make CMakeFiles/adventure.dir/deps/soloud/src/core/soloud_filter.cpp.i
.PHONY : deps/soloud/src/core/soloud_filter.cpp.i

deps/soloud/src/core/soloud_filter.s: deps/soloud/src/core/soloud_filter.cpp.s
.PHONY : deps/soloud/src/core/soloud_filter.s

# target to generate assembly for a file
deps/soloud/src/core/soloud_filter.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\adventure.dir\build.make CMakeFiles/adventure.dir/deps/soloud/src/core/soloud_filter.cpp.s
.PHONY : deps/soloud/src/core/soloud_filter.cpp.s

deps/soloud/src/core/soloud_misc.obj: deps/soloud/src/core/soloud_misc.cpp.obj
.PHONY : deps/soloud/src/core/soloud_misc.obj

# target to build an object file
deps/soloud/src/core/soloud_misc.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\adventure.dir\build.make CMakeFiles/adventure.dir/deps/soloud/src/core/soloud_misc.cpp.obj
.PHONY : deps/soloud/src/core/soloud_misc.cpp.obj

deps/soloud/src/core/soloud_misc.i: deps/soloud/src/core/soloud_misc.cpp.i
.PHONY : deps/soloud/src/core/soloud_misc.i

# target to preprocess a source file
deps/soloud/src/core/soloud_misc.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\adventure.dir\build.make CMakeFiles/adventure.dir/deps/soloud/src/core/soloud_misc.cpp.i
.PHONY : deps/soloud/src/core/soloud_misc.cpp.i

deps/soloud/src/core/soloud_misc.s: deps/soloud/src/core/soloud_misc.cpp.s
.PHONY : deps/soloud/src/core/soloud_misc.s

# target to generate assembly for a file
deps/soloud/src/core/soloud_misc.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\adventure.dir\build.make CMakeFiles/adventure.dir/deps/soloud/src/core/soloud_misc.cpp.s
.PHONY : deps/soloud/src/core/soloud_misc.cpp.s

deps/soloud/src/core/soloud_queue.obj: deps/soloud/src/core/soloud_queue.cpp.obj
.PHONY : deps/soloud/src/core/soloud_queue.obj

# target to build an object file
deps/soloud/src/core/soloud_queue.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\adventure.dir\build.make CMakeFiles/adventure.dir/deps/soloud/src/core/soloud_queue.cpp.obj
.PHONY : deps/soloud/src/core/soloud_queue.cpp.obj

deps/soloud/src/core/soloud_queue.i: deps/soloud/src/core/soloud_queue.cpp.i
.PHONY : deps/soloud/src/core/soloud_queue.i

# target to preprocess a source file
deps/soloud/src/core/soloud_queue.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\adventure.dir\build.make CMakeFiles/adventure.dir/deps/soloud/src/core/soloud_queue.cpp.i
.PHONY : deps/soloud/src/core/soloud_queue.cpp.i

deps/soloud/src/core/soloud_queue.s: deps/soloud/src/core/soloud_queue.cpp.s
.PHONY : deps/soloud/src/core/soloud_queue.s

# target to generate assembly for a file
deps/soloud/src/core/soloud_queue.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\adventure.dir\build.make CMakeFiles/adventure.dir/deps/soloud/src/core/soloud_queue.cpp.s
.PHONY : deps/soloud/src/core/soloud_queue.cpp.s

deps/soloud/src/core/soloud_thread.obj: deps/soloud/src/core/soloud_thread.cpp.obj
.PHONY : deps/soloud/src/core/soloud_thread.obj

# target to build an object file
deps/soloud/src/core/soloud_thread.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\adventure.dir\build.make CMakeFiles/adventure.dir/deps/soloud/src/core/soloud_thread.cpp.obj
.PHONY : deps/soloud/src/core/soloud_thread.cpp.obj

deps/soloud/src/core/soloud_thread.i: deps/soloud/src/core/soloud_thread.cpp.i
.PHONY : deps/soloud/src/core/soloud_thread.i

# target to preprocess a source file
deps/soloud/src/core/soloud_thread.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\adventure.dir\build.make CMakeFiles/adventure.dir/deps/soloud/src/core/soloud_thread.cpp.i
.PHONY : deps/soloud/src/core/soloud_thread.cpp.i

deps/soloud/src/core/soloud_thread.s: deps/soloud/src/core/soloud_thread.cpp.s
.PHONY : deps/soloud/src/core/soloud_thread.s

# target to generate assembly for a file
deps/soloud/src/core/soloud_thread.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\adventure.dir\build.make CMakeFiles/adventure.dir/deps/soloud/src/core/soloud_thread.cpp.s
.PHONY : deps/soloud/src/core/soloud_thread.cpp.s

src/AABBTree.obj: src/AABBTree.cpp.obj
.PHONY : src/AABBTree.obj

# target to build an object file
src/AABBTree.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\adventure.dir\build.make CMakeFiles/adventure.dir/src/AABBTree.cpp.obj
.PHONY : src/AABBTree.cpp.obj

src/AABBTree.i: src/AABBTree.cpp.i
.PHONY : src/AABBTree.i

# target to preprocess a source file
src/AABBTree.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\adventure.dir\build.make CMakeFiles/adventure.dir/src/AABBTree.cpp.i
.PHONY : src/AABBTree.cpp.i

src/AABBTree.s: src/AABBTree.cpp.s
.PHONY : src/AABBTree.s

# target to generate assembly for a file
src/AABBTree.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\adventure.dir\build.make CMakeFiles/adventure.dir/src/AABBTree.cpp.s
.PHONY : src/AABBTree.cpp.s

src/Angles.obj: src/Angles.cpp.obj
.PHONY : src/Angles.obj

# target to build an object file
src/Angles.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\adventure.dir\build.make CMakeFiles/adventure.dir/src/Angles.cpp.obj
.PHONY : src/Angles.cpp.obj

src/Angles.i: src/Angles.cpp.i
.PHONY : src/Angles.i

# target to preprocess a source file
src/Angles.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\adventure.dir\build.make CMakeFiles/adventure.dir/src/Angles.cpp.i
.PHONY : src/Angles.cpp.i

src/Angles.s: src/Angles.cpp.s
.PHONY : src/Angles.s

# target to generate assembly for a file
src/Angles.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\adventure.dir\build.make CMakeFiles/adventure.dir/src/Angles.cpp.s
.PHONY : src/Angles.cpp.s

src/Application.obj: src/Application.cpp.obj
.PHONY : src/Application.obj

# target to build an object file
src/Application.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\adventure.dir\build.make CMakeFiles/adventure.dir/src/Application.cpp.obj
.PHONY : src/Application.cpp.obj

src/Application.i: src/Application.cpp.i
.PHONY : src/Application.i

# target to preprocess a source file
src/Application.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\adventure.dir\build.make CMakeFiles/adventure.dir/src/Application.cpp.i
.PHONY : src/Application.cpp.i

src/Application.s: src/Application.cpp.s
.PHONY : src/Application.s

# target to generate assembly for a file
src/Application.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\adventure.dir\build.make CMakeFiles/adventure.dir/src/Application.cpp.s
.PHONY : src/Application.cpp.s

src/BoundingBoxRenderer.obj: src/BoundingBoxRenderer.cpp.obj
.PHONY : src/BoundingBoxRenderer.obj

# target to build an object file
src/BoundingBoxRenderer.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\adventure.dir\build.make CMakeFiles/adventure.dir/src/BoundingBoxRenderer.cpp.obj
.PHONY : src/BoundingBoxRenderer.cpp.obj

src/BoundingBoxRenderer.i: src/BoundingBoxRenderer.cpp.i
.PHONY : src/BoundingBoxRenderer.i

# target to preprocess a source file
src/BoundingBoxRenderer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\adventure.dir\build.make CMakeFiles/adventure.dir/src/BoundingBoxRenderer.cpp.i
.PHONY : src/BoundingBoxRenderer.cpp.i

src/BoundingBoxRenderer.s: src/BoundingBoxRenderer.cpp.s
.PHONY : src/BoundingBoxRenderer.s

# target to generate assembly for a file
src/BoundingBoxRenderer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\adventure.dir\build.make CMakeFiles/adventure.dir/src/BoundingBoxRenderer.cpp.s
.PHONY : src/BoundingBoxRenderer.cpp.s

src/BoxColorRenderer.obj: src/BoxColorRenderer.cpp.obj
.PHONY : src/BoxColorRenderer.obj

# target to build an object file
src/BoxColorRenderer.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\adventure.dir\build.make CMakeFiles/adventure.dir/src/BoxColorRenderer.cpp.obj
.PHONY : src/BoxColorRenderer.cpp.obj

src/BoxColorRenderer.i: src/BoxColorRenderer.cpp.i
.PHONY : src/BoxColorRenderer.i

# target to preprocess a source file
src/BoxColorRenderer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\adventure.dir\build.make CMakeFiles/adventure.dir/src/BoxColorRenderer.cpp.i
.PHONY : src/BoxColorRenderer.cpp.i

src/BoxColorRenderer.s: src/BoxColorRenderer.cpp.s
.PHONY : src/BoxColorRenderer.s

# target to generate assembly for a file
src/BoxColorRenderer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\adventure.dir\build.make CMakeFiles/adventure.dir/src/BoxColorRenderer.cpp.s
.PHONY : src/BoxColorRenderer.cpp.s

src/Camera.obj: src/Camera.cpp.obj
.PHONY : src/Camera.obj

# target to build an object file
src/Camera.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\adventure.dir\build.make CMakeFiles/adventure.dir/src/Camera.cpp.obj
.PHONY : src/Camera.cpp.obj

src/Camera.i: src/Camera.cpp.i
.PHONY : src/Camera.i

# target to preprocess a source file
src/Camera.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\adventure.dir\build.make CMakeFiles/adventure.dir/src/Camera.cpp.i
.PHONY : src/Camera.cpp.i

src/Camera.s: src/Camera.cpp.s
.PHONY : src/Camera.s

# target to generate assembly for a file
src/Camera.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\adventure.dir\build.make CMakeFiles/adventure.dir/src/Camera.cpp.s
.PHONY : src/Camera.cpp.s

src/Collider.obj: src/Collider.cpp.obj
.PHONY : src/Collider.obj

# target to build an object file
src/Collider.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\adventure.dir\build.make CMakeFiles/adventure.dir/src/Collider.cpp.obj
.PHONY : src/Collider.cpp.obj

src/Collider.i: src/Collider.cpp.i
.PHONY : src/Collider.i

# target to preprocess a source file
src/Collider.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\adventure.dir\build.make CMakeFiles/adventure.dir/src/Collider.cpp.i
.PHONY : src/Collider.cpp.i

src/Collider.s: src/Collider.cpp.s
.PHONY : src/Collider.s

# target to generate assembly for a file
src/Collider.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\adventure.dir\build.make CMakeFiles/adventure.dir/src/Collider.cpp.s
.PHONY : src/Collider.cpp.s

src/Collision.obj: src/Collision.cpp.obj
.PHONY : src/Collision.obj

# target to build an object file
src/Collision.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\adventure.dir\build.make CMakeFiles/adventure.dir/src/Collision.cpp.obj
.PHONY : src/Collision.cpp.obj

src/Collision.i: src/Collision.cpp.i
.PHONY : src/Collision.i

# target to preprocess a source file
src/Collision.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\adventure.dir\build.make CMakeFiles/adventure.dir/src/Collision.cpp.i
.PHONY : src/Collision.cpp.i

src/Collision.s: src/Collision.cpp.s
.PHONY : src/Collision.s

# target to generate assembly for a file
src/Collision.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\adventure.dir\build.make CMakeFiles/adventure.dir/src/Collision.cpp.s
.PHONY : src/Collision.cpp.s

src/CollisionMask.obj: src/CollisionMask.cpp.obj
.PHONY : src/CollisionMask.obj

# target to build an object file
src/CollisionMask.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\adventure.dir\build.make CMakeFiles/adventure.dir/src/CollisionMask.cpp.obj
.PHONY : src/CollisionMask.cpp.obj

src/CollisionMask.i: src/CollisionMask.cpp.i
.PHONY : src/CollisionMask.i

# target to preprocess a source file
src/CollisionMask.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\adventure.dir\build.make CMakeFiles/adventure.dir/src/CollisionMask.cpp.i
.PHONY : src/CollisionMask.cpp.i

src/CollisionMask.s: src/CollisionMask.cpp.s
.PHONY : src/CollisionMask.s

# target to generate assembly for a file
src/CollisionMask.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\adventure.dir\build.make CMakeFiles/adventure.dir/src/CollisionMask.cpp.s
.PHONY : src/CollisionMask.cpp.s

src/FastboiCore.obj: src/FastboiCore.cpp.obj
.PHONY : src/FastboiCore.obj

# target to build an object file
src/FastboiCore.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\adventure.dir\build.make CMakeFiles/adventure.dir/src/FastboiCore.cpp.obj
.PHONY : src/FastboiCore.cpp.obj

src/FastboiCore.i: src/FastboiCore.cpp.i
.PHONY : src/FastboiCore.i

# target to preprocess a source file
src/FastboiCore.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\adventure.dir\build.make CMakeFiles/adventure.dir/src/FastboiCore.cpp.i
.PHONY : src/FastboiCore.cpp.i

src/FastboiCore.s: src/FastboiCore.cpp.s
.PHONY : src/FastboiCore.s

# target to generate assembly for a file
src/FastboiCore.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\adventure.dir\build.make CMakeFiles/adventure.dir/src/FastboiCore.cpp.s
.PHONY : src/FastboiCore.cpp.s

src/GORef.obj: src/GORef.cpp.obj
.PHONY : src/GORef.obj

# target to build an object file
src/GORef.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\adventure.dir\build.make CMakeFiles/adventure.dir/src/GORef.cpp.obj
.PHONY : src/GORef.cpp.obj

src/GORef.i: src/GORef.cpp.i
.PHONY : src/GORef.i

# target to preprocess a source file
src/GORef.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\adventure.dir\build.make CMakeFiles/adventure.dir/src/GORef.cpp.i
.PHONY : src/GORef.cpp.i

src/GORef.s: src/GORef.cpp.s
.PHONY : src/GORef.s

# target to generate assembly for a file
src/GORef.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\adventure.dir\build.make CMakeFiles/adventure.dir/src/GORef.cpp.s
.PHONY : src/GORef.cpp.s

src/Gameobject.obj: src/Gameobject.cpp.obj
.PHONY : src/Gameobject.obj

# target to build an object file
src/Gameobject.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\adventure.dir\build.make CMakeFiles/adventure.dir/src/Gameobject.cpp.obj
.PHONY : src/Gameobject.cpp.obj

src/Gameobject.i: src/Gameobject.cpp.i
.PHONY : src/Gameobject.i

# target to preprocess a source file
src/Gameobject.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\adventure.dir\build.make CMakeFiles/adventure.dir/src/Gameobject.cpp.i
.PHONY : src/Gameobject.cpp.i

src/Gameobject.s: src/Gameobject.cpp.s
.PHONY : src/Gameobject.s

# target to generate assembly for a file
src/Gameobject.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\adventure.dir\build.make CMakeFiles/adventure.dir/src/Gameobject.cpp.s
.PHONY : src/Gameobject.cpp.s

src/GameobjectAllocator.obj: src/GameobjectAllocator.cpp.obj
.PHONY : src/GameobjectAllocator.obj

# target to build an object file
src/GameobjectAllocator.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\adventure.dir\build.make CMakeFiles/adventure.dir/src/GameobjectAllocator.cpp.obj
.PHONY : src/GameobjectAllocator.cpp.obj

src/GameobjectAllocator.i: src/GameobjectAllocator.cpp.i
.PHONY : src/GameobjectAllocator.i

# target to preprocess a source file
src/GameobjectAllocator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\adventure.dir\build.make CMakeFiles/adventure.dir/src/GameobjectAllocator.cpp.i
.PHONY : src/GameobjectAllocator.cpp.i

src/GameobjectAllocator.s: src/GameobjectAllocator.cpp.s
.PHONY : src/GameobjectAllocator.s

# target to generate assembly for a file
src/GameobjectAllocator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\adventure.dir\build.make CMakeFiles/adventure.dir/src/GameobjectAllocator.cpp.s
.PHONY : src/GameobjectAllocator.cpp.s

src/Input.obj: src/Input.cpp.obj
.PHONY : src/Input.obj

# target to build an object file
src/Input.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\adventure.dir\build.make CMakeFiles/adventure.dir/src/Input.cpp.obj
.PHONY : src/Input.cpp.obj

src/Input.i: src/Input.cpp.i
.PHONY : src/Input.i

# target to preprocess a source file
src/Input.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\adventure.dir\build.make CMakeFiles/adventure.dir/src/Input.cpp.i
.PHONY : src/Input.cpp.i

src/Input.s: src/Input.cpp.s
.PHONY : src/Input.s

# target to generate assembly for a file
src/Input.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\adventure.dir\build.make CMakeFiles/adventure.dir/src/Input.cpp.s
.PHONY : src/Input.cpp.s

src/RectUI.obj: src/RectUI.cpp.obj
.PHONY : src/RectUI.obj

# target to build an object file
src/RectUI.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\adventure.dir\build.make CMakeFiles/adventure.dir/src/RectUI.cpp.obj
.PHONY : src/RectUI.cpp.obj

src/RectUI.i: src/RectUI.cpp.i
.PHONY : src/RectUI.i

# target to preprocess a source file
src/RectUI.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\adventure.dir\build.make CMakeFiles/adventure.dir/src/RectUI.cpp.i
.PHONY : src/RectUI.cpp.i

src/RectUI.s: src/RectUI.cpp.s
.PHONY : src/RectUI.s

# target to generate assembly for a file
src/RectUI.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\adventure.dir\build.make CMakeFiles/adventure.dir/src/RectUI.cpp.s
.PHONY : src/RectUI.cpp.s

src/Renderer.obj: src/Renderer.cpp.obj
.PHONY : src/Renderer.obj

# target to build an object file
src/Renderer.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\adventure.dir\build.make CMakeFiles/adventure.dir/src/Renderer.cpp.obj
.PHONY : src/Renderer.cpp.obj

src/Renderer.i: src/Renderer.cpp.i
.PHONY : src/Renderer.i

# target to preprocess a source file
src/Renderer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\adventure.dir\build.make CMakeFiles/adventure.dir/src/Renderer.cpp.i
.PHONY : src/Renderer.cpp.i

src/Renderer.s: src/Renderer.cpp.s
.PHONY : src/Renderer.s

# target to generate assembly for a file
src/Renderer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\adventure.dir\build.make CMakeFiles/adventure.dir/src/Renderer.cpp.s
.PHONY : src/Renderer.cpp.s

src/Rendering.obj: src/Rendering.cpp.obj
.PHONY : src/Rendering.obj

# target to build an object file
src/Rendering.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\adventure.dir\build.make CMakeFiles/adventure.dir/src/Rendering.cpp.obj
.PHONY : src/Rendering.cpp.obj

src/Rendering.i: src/Rendering.cpp.i
.PHONY : src/Rendering.i

# target to preprocess a source file
src/Rendering.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\adventure.dir\build.make CMakeFiles/adventure.dir/src/Rendering.cpp.i
.PHONY : src/Rendering.cpp.i

src/Rendering.s: src/Rendering.cpp.s
.PHONY : src/Rendering.s

# target to generate assembly for a file
src/Rendering.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\adventure.dir\build.make CMakeFiles/adventure.dir/src/Rendering.cpp.s
.PHONY : src/Rendering.cpp.s

src/RepeatRenderer.obj: src/RepeatRenderer.cpp.obj
.PHONY : src/RepeatRenderer.obj

# target to build an object file
src/RepeatRenderer.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\adventure.dir\build.make CMakeFiles/adventure.dir/src/RepeatRenderer.cpp.obj
.PHONY : src/RepeatRenderer.cpp.obj

src/RepeatRenderer.i: src/RepeatRenderer.cpp.i
.PHONY : src/RepeatRenderer.i

# target to preprocess a source file
src/RepeatRenderer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\adventure.dir\build.make CMakeFiles/adventure.dir/src/RepeatRenderer.cpp.i
.PHONY : src/RepeatRenderer.cpp.i

src/RepeatRenderer.s: src/RepeatRenderer.cpp.s
.PHONY : src/RepeatRenderer.s

# target to generate assembly for a file
src/RepeatRenderer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\adventure.dir\build.make CMakeFiles/adventure.dir/src/RepeatRenderer.cpp.s
.PHONY : src/RepeatRenderer.cpp.s

src/Resources.obj: src/Resources.cpp.obj
.PHONY : src/Resources.obj

# target to build an object file
src/Resources.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\adventure.dir\build.make CMakeFiles/adventure.dir/src/Resources.cpp.obj
.PHONY : src/Resources.cpp.obj

src/Resources.i: src/Resources.cpp.i
.PHONY : src/Resources.i

# target to preprocess a source file
src/Resources.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\adventure.dir\build.make CMakeFiles/adventure.dir/src/Resources.cpp.i
.PHONY : src/Resources.cpp.i

src/Resources.s: src/Resources.cpp.s
.PHONY : src/Resources.s

# target to generate assembly for a file
src/Resources.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\adventure.dir\build.make CMakeFiles/adventure.dir/src/Resources.cpp.s
.PHONY : src/Resources.cpp.s

src/Rigidbody.obj: src/Rigidbody.cpp.obj
.PHONY : src/Rigidbody.obj

# target to build an object file
src/Rigidbody.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\adventure.dir\build.make CMakeFiles/adventure.dir/src/Rigidbody.cpp.obj
.PHONY : src/Rigidbody.cpp.obj

src/Rigidbody.i: src/Rigidbody.cpp.i
.PHONY : src/Rigidbody.i

# target to preprocess a source file
src/Rigidbody.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\adventure.dir\build.make CMakeFiles/adventure.dir/src/Rigidbody.cpp.i
.PHONY : src/Rigidbody.cpp.i

src/Rigidbody.s: src/Rigidbody.cpp.s
.PHONY : src/Rigidbody.s

# target to generate assembly for a file
src/Rigidbody.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\adventure.dir\build.make CMakeFiles/adventure.dir/src/Rigidbody.cpp.s
.PHONY : src/Rigidbody.cpp.s

src/ScreenElement.obj: src/ScreenElement.cpp.obj
.PHONY : src/ScreenElement.obj

# target to build an object file
src/ScreenElement.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\adventure.dir\build.make CMakeFiles/adventure.dir/src/ScreenElement.cpp.obj
.PHONY : src/ScreenElement.cpp.obj

src/ScreenElement.i: src/ScreenElement.cpp.i
.PHONY : src/ScreenElement.i

# target to preprocess a source file
src/ScreenElement.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\adventure.dir\build.make CMakeFiles/adventure.dir/src/ScreenElement.cpp.i
.PHONY : src/ScreenElement.cpp.i

src/ScreenElement.s: src/ScreenElement.cpp.s
.PHONY : src/ScreenElement.s

# target to generate assembly for a file
src/ScreenElement.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\adventure.dir\build.make CMakeFiles/adventure.dir/src/ScreenElement.cpp.s
.PHONY : src/ScreenElement.cpp.s

src/Shape.obj: src/Shape.cpp.obj
.PHONY : src/Shape.obj

# target to build an object file
src/Shape.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\adventure.dir\build.make CMakeFiles/adventure.dir/src/Shape.cpp.obj
.PHONY : src/Shape.cpp.obj

src/Shape.i: src/Shape.cpp.i
.PHONY : src/Shape.i

# target to preprocess a source file
src/Shape.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\adventure.dir\build.make CMakeFiles/adventure.dir/src/Shape.cpp.i
.PHONY : src/Shape.cpp.i

src/Shape.s: src/Shape.cpp.s
.PHONY : src/Shape.s

# target to generate assembly for a file
src/Shape.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\adventure.dir\build.make CMakeFiles/adventure.dir/src/Shape.cpp.s
.PHONY : src/Shape.cpp.s

src/Speaker.obj: src/Speaker.cpp.obj
.PHONY : src/Speaker.obj

# target to build an object file
src/Speaker.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\adventure.dir\build.make CMakeFiles/adventure.dir/src/Speaker.cpp.obj
.PHONY : src/Speaker.cpp.obj

src/Speaker.i: src/Speaker.cpp.i
.PHONY : src/Speaker.i

# target to preprocess a source file
src/Speaker.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\adventure.dir\build.make CMakeFiles/adventure.dir/src/Speaker.cpp.i
.PHONY : src/Speaker.cpp.i

src/Speaker.s: src/Speaker.cpp.s
.PHONY : src/Speaker.s

# target to generate assembly for a file
src/Speaker.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\adventure.dir\build.make CMakeFiles/adventure.dir/src/Speaker.cpp.s
.PHONY : src/Speaker.cpp.s

src/SpriteRenderer.obj: src/SpriteRenderer.cpp.obj
.PHONY : src/SpriteRenderer.obj

# target to build an object file
src/SpriteRenderer.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\adventure.dir\build.make CMakeFiles/adventure.dir/src/SpriteRenderer.cpp.obj
.PHONY : src/SpriteRenderer.cpp.obj

src/SpriteRenderer.i: src/SpriteRenderer.cpp.i
.PHONY : src/SpriteRenderer.i

# target to preprocess a source file
src/SpriteRenderer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\adventure.dir\build.make CMakeFiles/adventure.dir/src/SpriteRenderer.cpp.i
.PHONY : src/SpriteRenderer.cpp.i

src/SpriteRenderer.s: src/SpriteRenderer.cpp.s
.PHONY : src/SpriteRenderer.s

# target to generate assembly for a file
src/SpriteRenderer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\adventure.dir\build.make CMakeFiles/adventure.dir/src/SpriteRenderer.cpp.s
.PHONY : src/SpriteRenderer.cpp.s

src/Texture.obj: src/Texture.cpp.obj
.PHONY : src/Texture.obj

# target to build an object file
src/Texture.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\adventure.dir\build.make CMakeFiles/adventure.dir/src/Texture.cpp.obj
.PHONY : src/Texture.cpp.obj

src/Texture.i: src/Texture.cpp.i
.PHONY : src/Texture.i

# target to preprocess a source file
src/Texture.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\adventure.dir\build.make CMakeFiles/adventure.dir/src/Texture.cpp.i
.PHONY : src/Texture.cpp.i

src/Texture.s: src/Texture.cpp.s
.PHONY : src/Texture.s

# target to generate assembly for a file
src/Texture.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\adventure.dir\build.make CMakeFiles/adventure.dir/src/Texture.cpp.s
.PHONY : src/Texture.cpp.s

src/Transform.obj: src/Transform.cpp.obj
.PHONY : src/Transform.obj

# target to build an object file
src/Transform.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\adventure.dir\build.make CMakeFiles/adventure.dir/src/Transform.cpp.obj
.PHONY : src/Transform.cpp.obj

src/Transform.i: src/Transform.cpp.i
.PHONY : src/Transform.i

# target to preprocess a source file
src/Transform.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\adventure.dir\build.make CMakeFiles/adventure.dir/src/Transform.cpp.i
.PHONY : src/Transform.cpp.i

src/Transform.s: src/Transform.cpp.s
.PHONY : src/Transform.s

# target to generate assembly for a file
src/Transform.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\adventure.dir\build.make CMakeFiles/adventure.dir/src/Transform.cpp.s
.PHONY : src/Transform.cpp.s

src/UI/Screen.obj: src/UI/Screen.cpp.obj
.PHONY : src/UI/Screen.obj

# target to build an object file
src/UI/Screen.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\adventure.dir\build.make CMakeFiles/adventure.dir/src/UI/Screen.cpp.obj
.PHONY : src/UI/Screen.cpp.obj

src/UI/Screen.i: src/UI/Screen.cpp.i
.PHONY : src/UI/Screen.i

# target to preprocess a source file
src/UI/Screen.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\adventure.dir\build.make CMakeFiles/adventure.dir/src/UI/Screen.cpp.i
.PHONY : src/UI/Screen.cpp.i

src/UI/Screen.s: src/UI/Screen.cpp.s
.PHONY : src/UI/Screen.s

# target to generate assembly for a file
src/UI/Screen.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\adventure.dir\build.make CMakeFiles/adventure.dir/src/UI/Screen.cpp.s
.PHONY : src/UI/Screen.cpp.s

src/UITexture.obj: src/UITexture.cpp.obj
.PHONY : src/UITexture.obj

# target to build an object file
src/UITexture.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\adventure.dir\build.make CMakeFiles/adventure.dir/src/UITexture.cpp.obj
.PHONY : src/UITexture.cpp.obj

src/UITexture.i: src/UITexture.cpp.i
.PHONY : src/UITexture.i

# target to preprocess a source file
src/UITexture.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\adventure.dir\build.make CMakeFiles/adventure.dir/src/UITexture.cpp.i
.PHONY : src/UITexture.cpp.i

src/UITexture.s: src/UITexture.cpp.s
.PHONY : src/UITexture.s

# target to generate assembly for a file
src/UITexture.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\adventure.dir\build.make CMakeFiles/adventure.dir/src/UITexture.cpp.s
.PHONY : src/UITexture.cpp.s

src/Utility.obj: src/Utility.cpp.obj
.PHONY : src/Utility.obj

# target to build an object file
src/Utility.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\adventure.dir\build.make CMakeFiles/adventure.dir/src/Utility.cpp.obj
.PHONY : src/Utility.cpp.obj

src/Utility.i: src/Utility.cpp.i
.PHONY : src/Utility.i

# target to preprocess a source file
src/Utility.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\adventure.dir\build.make CMakeFiles/adventure.dir/src/Utility.cpp.i
.PHONY : src/Utility.cpp.i

src/Utility.s: src/Utility.cpp.s
.PHONY : src/Utility.s

# target to generate assembly for a file
src/Utility.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\adventure.dir\build.make CMakeFiles/adventure.dir/src/Utility.cpp.s
.PHONY : src/Utility.cpp.s

src/WireframeRenderer.obj: src/WireframeRenderer.cpp.obj
.PHONY : src/WireframeRenderer.obj

# target to build an object file
src/WireframeRenderer.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\adventure.dir\build.make CMakeFiles/adventure.dir/src/WireframeRenderer.cpp.obj
.PHONY : src/WireframeRenderer.cpp.obj

src/WireframeRenderer.i: src/WireframeRenderer.cpp.i
.PHONY : src/WireframeRenderer.i

# target to preprocess a source file
src/WireframeRenderer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\adventure.dir\build.make CMakeFiles/adventure.dir/src/WireframeRenderer.cpp.i
.PHONY : src/WireframeRenderer.cpp.i

src/WireframeRenderer.s: src/WireframeRenderer.cpp.s
.PHONY : src/WireframeRenderer.s

# target to generate assembly for a file
src/WireframeRenderer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\adventure.dir\build.make CMakeFiles/adventure.dir/src/WireframeRenderer.cpp.s
.PHONY : src/WireframeRenderer.cpp.s

src/adventure/Bridge.obj: src/adventure/Bridge.cpp.obj
.PHONY : src/adventure/Bridge.obj

# target to build an object file
src/adventure/Bridge.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\adventure.dir\build.make CMakeFiles/adventure.dir/src/adventure/Bridge.cpp.obj
.PHONY : src/adventure/Bridge.cpp.obj

src/adventure/Bridge.i: src/adventure/Bridge.cpp.i
.PHONY : src/adventure/Bridge.i

# target to preprocess a source file
src/adventure/Bridge.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\adventure.dir\build.make CMakeFiles/adventure.dir/src/adventure/Bridge.cpp.i
.PHONY : src/adventure/Bridge.cpp.i

src/adventure/Bridge.s: src/adventure/Bridge.cpp.s
.PHONY : src/adventure/Bridge.s

# target to generate assembly for a file
src/adventure/Bridge.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\adventure.dir\build.make CMakeFiles/adventure.dir/src/adventure/Bridge.cpp.s
.PHONY : src/adventure/Bridge.cpp.s

src/adventure/Chalise.obj: src/adventure/Chalise.cpp.obj
.PHONY : src/adventure/Chalise.obj

# target to build an object file
src/adventure/Chalise.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\adventure.dir\build.make CMakeFiles/adventure.dir/src/adventure/Chalise.cpp.obj
.PHONY : src/adventure/Chalise.cpp.obj

src/adventure/Chalise.i: src/adventure/Chalise.cpp.i
.PHONY : src/adventure/Chalise.i

# target to preprocess a source file
src/adventure/Chalise.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\adventure.dir\build.make CMakeFiles/adventure.dir/src/adventure/Chalise.cpp.i
.PHONY : src/adventure/Chalise.cpp.i

src/adventure/Chalise.s: src/adventure/Chalise.cpp.s
.PHONY : src/adventure/Chalise.s

# target to generate assembly for a file
src/adventure/Chalise.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\adventure.dir\build.make CMakeFiles/adventure.dir/src/adventure/Chalise.cpp.s
.PHONY : src/adventure/Chalise.cpp.s

src/adventure/Dragon.obj: src/adventure/Dragon.cpp.obj
.PHONY : src/adventure/Dragon.obj

# target to build an object file
src/adventure/Dragon.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\adventure.dir\build.make CMakeFiles/adventure.dir/src/adventure/Dragon.cpp.obj
.PHONY : src/adventure/Dragon.cpp.obj

src/adventure/Dragon.i: src/adventure/Dragon.cpp.i
.PHONY : src/adventure/Dragon.i

# target to preprocess a source file
src/adventure/Dragon.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\adventure.dir\build.make CMakeFiles/adventure.dir/src/adventure/Dragon.cpp.i
.PHONY : src/adventure/Dragon.cpp.i

src/adventure/Dragon.s: src/adventure/Dragon.cpp.s
.PHONY : src/adventure/Dragon.s

# target to generate assembly for a file
src/adventure/Dragon.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\adventure.dir\build.make CMakeFiles/adventure.dir/src/adventure/Dragon.cpp.s
.PHONY : src/adventure/Dragon.cpp.s

src/adventure/Game.obj: src/adventure/Game.cpp.obj
.PHONY : src/adventure/Game.obj

# target to build an object file
src/adventure/Game.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\adventure.dir\build.make CMakeFiles/adventure.dir/src/adventure/Game.cpp.obj
.PHONY : src/adventure/Game.cpp.obj

src/adventure/Game.i: src/adventure/Game.cpp.i
.PHONY : src/adventure/Game.i

# target to preprocess a source file
src/adventure/Game.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\adventure.dir\build.make CMakeFiles/adventure.dir/src/adventure/Game.cpp.i
.PHONY : src/adventure/Game.cpp.i

src/adventure/Game.s: src/adventure/Game.cpp.s
.PHONY : src/adventure/Game.s

# target to generate assembly for a file
src/adventure/Game.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\adventure.dir\build.make CMakeFiles/adventure.dir/src/adventure/Game.cpp.s
.PHONY : src/adventure/Game.cpp.s

src/adventure/GameManager.obj: src/adventure/GameManager.cpp.obj
.PHONY : src/adventure/GameManager.obj

# target to build an object file
src/adventure/GameManager.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\adventure.dir\build.make CMakeFiles/adventure.dir/src/adventure/GameManager.cpp.obj
.PHONY : src/adventure/GameManager.cpp.obj

src/adventure/GameManager.i: src/adventure/GameManager.cpp.i
.PHONY : src/adventure/GameManager.i

# target to preprocess a source file
src/adventure/GameManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\adventure.dir\build.make CMakeFiles/adventure.dir/src/adventure/GameManager.cpp.i
.PHONY : src/adventure/GameManager.cpp.i

src/adventure/GameManager.s: src/adventure/GameManager.cpp.s
.PHONY : src/adventure/GameManager.s

# target to generate assembly for a file
src/adventure/GameManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\adventure.dir\build.make CMakeFiles/adventure.dir/src/adventure/GameManager.cpp.s
.PHONY : src/adventure/GameManager.cpp.s

src/adventure/Gate.obj: src/adventure/Gate.cpp.obj
.PHONY : src/adventure/Gate.obj

# target to build an object file
src/adventure/Gate.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\adventure.dir\build.make CMakeFiles/adventure.dir/src/adventure/Gate.cpp.obj
.PHONY : src/adventure/Gate.cpp.obj

src/adventure/Gate.i: src/adventure/Gate.cpp.i
.PHONY : src/adventure/Gate.i

# target to preprocess a source file
src/adventure/Gate.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\adventure.dir\build.make CMakeFiles/adventure.dir/src/adventure/Gate.cpp.i
.PHONY : src/adventure/Gate.cpp.i

src/adventure/Gate.s: src/adventure/Gate.cpp.s
.PHONY : src/adventure/Gate.s

# target to generate assembly for a file
src/adventure/Gate.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\adventure.dir\build.make CMakeFiles/adventure.dir/src/adventure/Gate.cpp.s
.PHONY : src/adventure/Gate.cpp.s

src/adventure/Item.obj: src/adventure/Item.cpp.obj
.PHONY : src/adventure/Item.obj

# target to build an object file
src/adventure/Item.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\adventure.dir\build.make CMakeFiles/adventure.dir/src/adventure/Item.cpp.obj
.PHONY : src/adventure/Item.cpp.obj

src/adventure/Item.i: src/adventure/Item.cpp.i
.PHONY : src/adventure/Item.i

# target to preprocess a source file
src/adventure/Item.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\adventure.dir\build.make CMakeFiles/adventure.dir/src/adventure/Item.cpp.i
.PHONY : src/adventure/Item.cpp.i

src/adventure/Item.s: src/adventure/Item.cpp.s
.PHONY : src/adventure/Item.s

# target to generate assembly for a file
src/adventure/Item.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\adventure.dir\build.make CMakeFiles/adventure.dir/src/adventure/Item.cpp.s
.PHONY : src/adventure/Item.cpp.s

src/adventure/Layouts.obj: src/adventure/Layouts.cpp.obj
.PHONY : src/adventure/Layouts.obj

# target to build an object file
src/adventure/Layouts.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\adventure.dir\build.make CMakeFiles/adventure.dir/src/adventure/Layouts.cpp.obj
.PHONY : src/adventure/Layouts.cpp.obj

src/adventure/Layouts.i: src/adventure/Layouts.cpp.i
.PHONY : src/adventure/Layouts.i

# target to preprocess a source file
src/adventure/Layouts.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\adventure.dir\build.make CMakeFiles/adventure.dir/src/adventure/Layouts.cpp.i
.PHONY : src/adventure/Layouts.cpp.i

src/adventure/Layouts.s: src/adventure/Layouts.cpp.s
.PHONY : src/adventure/Layouts.s

# target to generate assembly for a file
src/adventure/Layouts.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\adventure.dir\build.make CMakeFiles/adventure.dir/src/adventure/Layouts.cpp.s
.PHONY : src/adventure/Layouts.cpp.s

src/adventure/Level.obj: src/adventure/Level.cpp.obj
.PHONY : src/adventure/Level.obj

# target to build an object file
src/adventure/Level.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\adventure.dir\build.make CMakeFiles/adventure.dir/src/adventure/Level.cpp.obj
.PHONY : src/adventure/Level.cpp.obj

src/adventure/Level.i: src/adventure/Level.cpp.i
.PHONY : src/adventure/Level.i

# target to preprocess a source file
src/adventure/Level.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\adventure.dir\build.make CMakeFiles/adventure.dir/src/adventure/Level.cpp.i
.PHONY : src/adventure/Level.cpp.i

src/adventure/Level.s: src/adventure/Level.cpp.s
.PHONY : src/adventure/Level.s

# target to generate assembly for a file
src/adventure/Level.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\adventure.dir\build.make CMakeFiles/adventure.dir/src/adventure/Level.cpp.s
.PHONY : src/adventure/Level.cpp.s

src/adventure/Magnet.obj: src/adventure/Magnet.cpp.obj
.PHONY : src/adventure/Magnet.obj

# target to build an object file
src/adventure/Magnet.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\adventure.dir\build.make CMakeFiles/adventure.dir/src/adventure/Magnet.cpp.obj
.PHONY : src/adventure/Magnet.cpp.obj

src/adventure/Magnet.i: src/adventure/Magnet.cpp.i
.PHONY : src/adventure/Magnet.i

# target to preprocess a source file
src/adventure/Magnet.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\adventure.dir\build.make CMakeFiles/adventure.dir/src/adventure/Magnet.cpp.i
.PHONY : src/adventure/Magnet.cpp.i

src/adventure/Magnet.s: src/adventure/Magnet.cpp.s
.PHONY : src/adventure/Magnet.s

# target to generate assembly for a file
src/adventure/Magnet.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\adventure.dir\build.make CMakeFiles/adventure.dir/src/adventure/Magnet.cpp.s
.PHONY : src/adventure/Magnet.cpp.s

src/adventure/Player.obj: src/adventure/Player.cpp.obj
.PHONY : src/adventure/Player.obj

# target to build an object file
src/adventure/Player.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\adventure.dir\build.make CMakeFiles/adventure.dir/src/adventure/Player.cpp.obj
.PHONY : src/adventure/Player.cpp.obj

src/adventure/Player.i: src/adventure/Player.cpp.i
.PHONY : src/adventure/Player.i

# target to preprocess a source file
src/adventure/Player.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\adventure.dir\build.make CMakeFiles/adventure.dir/src/adventure/Player.cpp.i
.PHONY : src/adventure/Player.cpp.i

src/adventure/Player.s: src/adventure/Player.cpp.s
.PHONY : src/adventure/Player.s

# target to generate assembly for a file
src/adventure/Player.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\adventure.dir\build.make CMakeFiles/adventure.dir/src/adventure/Player.cpp.s
.PHONY : src/adventure/Player.cpp.s

src/adventure/Room.obj: src/adventure/Room.cpp.obj
.PHONY : src/adventure/Room.obj

# target to build an object file
src/adventure/Room.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\adventure.dir\build.make CMakeFiles/adventure.dir/src/adventure/Room.cpp.obj
.PHONY : src/adventure/Room.cpp.obj

src/adventure/Room.i: src/adventure/Room.cpp.i
.PHONY : src/adventure/Room.i

# target to preprocess a source file
src/adventure/Room.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\adventure.dir\build.make CMakeFiles/adventure.dir/src/adventure/Room.cpp.i
.PHONY : src/adventure/Room.cpp.i

src/adventure/Room.s: src/adventure/Room.cpp.s
.PHONY : src/adventure/Room.s

# target to generate assembly for a file
src/adventure/Room.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\adventure.dir\build.make CMakeFiles/adventure.dir/src/adventure/Room.cpp.s
.PHONY : src/adventure/Room.cpp.s

src/adventure/main.obj: src/adventure/main.cpp.obj
.PHONY : src/adventure/main.obj

# target to build an object file
src/adventure/main.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\adventure.dir\build.make CMakeFiles/adventure.dir/src/adventure/main.cpp.obj
.PHONY : src/adventure/main.cpp.obj

src/adventure/main.i: src/adventure/main.cpp.i
.PHONY : src/adventure/main.i

# target to preprocess a source file
src/adventure/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\adventure.dir\build.make CMakeFiles/adventure.dir/src/adventure/main.cpp.i
.PHONY : src/adventure/main.cpp.i

src/adventure/main.s: src/adventure/main.cpp.s
.PHONY : src/adventure/main.s

# target to generate assembly for a file
src/adventure/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\adventure.dir\build.make CMakeFiles/adventure.dir/src/adventure/main.cpp.s
.PHONY : src/adventure/main.cpp.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... edit_cache
	@echo ... rebuild_cache
	@echo ... adventure
	@echo ... deps/soloud/src/audiosource/wav/dr_impl.obj
	@echo ... deps/soloud/src/audiosource/wav/dr_impl.i
	@echo ... deps/soloud/src/audiosource/wav/dr_impl.s
	@echo ... deps/soloud/src/audiosource/wav/soloud_wav.obj
	@echo ... deps/soloud/src/audiosource/wav/soloud_wav.i
	@echo ... deps/soloud/src/audiosource/wav/soloud_wav.s
	@echo ... deps/soloud/src/audiosource/wav/soloud_wavstream.obj
	@echo ... deps/soloud/src/audiosource/wav/soloud_wavstream.i
	@echo ... deps/soloud/src/audiosource/wav/soloud_wavstream.s
	@echo ... deps/soloud/src/audiosource/wav/stb_vorbis.obj
	@echo ... deps/soloud/src/audiosource/wav/stb_vorbis.i
	@echo ... deps/soloud/src/audiosource/wav/stb_vorbis.s
	@echo ... deps/soloud/src/backend/sdl2_static/soloud_sdl2_static.obj
	@echo ... deps/soloud/src/backend/sdl2_static/soloud_sdl2_static.i
	@echo ... deps/soloud/src/backend/sdl2_static/soloud_sdl2_static.s
	@echo ... deps/soloud/src/core/soloud.obj
	@echo ... deps/soloud/src/core/soloud.i
	@echo ... deps/soloud/src/core/soloud.s
	@echo ... deps/soloud/src/core/soloud_audiosource.obj
	@echo ... deps/soloud/src/core/soloud_audiosource.i
	@echo ... deps/soloud/src/core/soloud_audiosource.s
	@echo ... deps/soloud/src/core/soloud_bus.obj
	@echo ... deps/soloud/src/core/soloud_bus.i
	@echo ... deps/soloud/src/core/soloud_bus.s
	@echo ... deps/soloud/src/core/soloud_core_3d.obj
	@echo ... deps/soloud/src/core/soloud_core_3d.i
	@echo ... deps/soloud/src/core/soloud_core_3d.s
	@echo ... deps/soloud/src/core/soloud_core_basicops.obj
	@echo ... deps/soloud/src/core/soloud_core_basicops.i
	@echo ... deps/soloud/src/core/soloud_core_basicops.s
	@echo ... deps/soloud/src/core/soloud_core_faderops.obj
	@echo ... deps/soloud/src/core/soloud_core_faderops.i
	@echo ... deps/soloud/src/core/soloud_core_faderops.s
	@echo ... deps/soloud/src/core/soloud_core_filterops.obj
	@echo ... deps/soloud/src/core/soloud_core_filterops.i
	@echo ... deps/soloud/src/core/soloud_core_filterops.s
	@echo ... deps/soloud/src/core/soloud_core_getters.obj
	@echo ... deps/soloud/src/core/soloud_core_getters.i
	@echo ... deps/soloud/src/core/soloud_core_getters.s
	@echo ... deps/soloud/src/core/soloud_core_setters.obj
	@echo ... deps/soloud/src/core/soloud_core_setters.i
	@echo ... deps/soloud/src/core/soloud_core_setters.s
	@echo ... deps/soloud/src/core/soloud_core_voicegroup.obj
	@echo ... deps/soloud/src/core/soloud_core_voicegroup.i
	@echo ... deps/soloud/src/core/soloud_core_voicegroup.s
	@echo ... deps/soloud/src/core/soloud_core_voiceops.obj
	@echo ... deps/soloud/src/core/soloud_core_voiceops.i
	@echo ... deps/soloud/src/core/soloud_core_voiceops.s
	@echo ... deps/soloud/src/core/soloud_fader.obj
	@echo ... deps/soloud/src/core/soloud_fader.i
	@echo ... deps/soloud/src/core/soloud_fader.s
	@echo ... deps/soloud/src/core/soloud_fft.obj
	@echo ... deps/soloud/src/core/soloud_fft.i
	@echo ... deps/soloud/src/core/soloud_fft.s
	@echo ... deps/soloud/src/core/soloud_fft_lut.obj
	@echo ... deps/soloud/src/core/soloud_fft_lut.i
	@echo ... deps/soloud/src/core/soloud_fft_lut.s
	@echo ... deps/soloud/src/core/soloud_file.obj
	@echo ... deps/soloud/src/core/soloud_file.i
	@echo ... deps/soloud/src/core/soloud_file.s
	@echo ... deps/soloud/src/core/soloud_filter.obj
	@echo ... deps/soloud/src/core/soloud_filter.i
	@echo ... deps/soloud/src/core/soloud_filter.s
	@echo ... deps/soloud/src/core/soloud_misc.obj
	@echo ... deps/soloud/src/core/soloud_misc.i
	@echo ... deps/soloud/src/core/soloud_misc.s
	@echo ... deps/soloud/src/core/soloud_queue.obj
	@echo ... deps/soloud/src/core/soloud_queue.i
	@echo ... deps/soloud/src/core/soloud_queue.s
	@echo ... deps/soloud/src/core/soloud_thread.obj
	@echo ... deps/soloud/src/core/soloud_thread.i
	@echo ... deps/soloud/src/core/soloud_thread.s
	@echo ... src/AABBTree.obj
	@echo ... src/AABBTree.i
	@echo ... src/AABBTree.s
	@echo ... src/Angles.obj
	@echo ... src/Angles.i
	@echo ... src/Angles.s
	@echo ... src/Application.obj
	@echo ... src/Application.i
	@echo ... src/Application.s
	@echo ... src/BoundingBoxRenderer.obj
	@echo ... src/BoundingBoxRenderer.i
	@echo ... src/BoundingBoxRenderer.s
	@echo ... src/BoxColorRenderer.obj
	@echo ... src/BoxColorRenderer.i
	@echo ... src/BoxColorRenderer.s
	@echo ... src/Camera.obj
	@echo ... src/Camera.i
	@echo ... src/Camera.s
	@echo ... src/Collider.obj
	@echo ... src/Collider.i
	@echo ... src/Collider.s
	@echo ... src/Collision.obj
	@echo ... src/Collision.i
	@echo ... src/Collision.s
	@echo ... src/CollisionMask.obj
	@echo ... src/CollisionMask.i
	@echo ... src/CollisionMask.s
	@echo ... src/FastboiCore.obj
	@echo ... src/FastboiCore.i
	@echo ... src/FastboiCore.s
	@echo ... src/GORef.obj
	@echo ... src/GORef.i
	@echo ... src/GORef.s
	@echo ... src/Gameobject.obj
	@echo ... src/Gameobject.i
	@echo ... src/Gameobject.s
	@echo ... src/GameobjectAllocator.obj
	@echo ... src/GameobjectAllocator.i
	@echo ... src/GameobjectAllocator.s
	@echo ... src/Input.obj
	@echo ... src/Input.i
	@echo ... src/Input.s
	@echo ... src/RectUI.obj
	@echo ... src/RectUI.i
	@echo ... src/RectUI.s
	@echo ... src/Renderer.obj
	@echo ... src/Renderer.i
	@echo ... src/Renderer.s
	@echo ... src/Rendering.obj
	@echo ... src/Rendering.i
	@echo ... src/Rendering.s
	@echo ... src/RepeatRenderer.obj
	@echo ... src/RepeatRenderer.i
	@echo ... src/RepeatRenderer.s
	@echo ... src/Resources.obj
	@echo ... src/Resources.i
	@echo ... src/Resources.s
	@echo ... src/Rigidbody.obj
	@echo ... src/Rigidbody.i
	@echo ... src/Rigidbody.s
	@echo ... src/ScreenElement.obj
	@echo ... src/ScreenElement.i
	@echo ... src/ScreenElement.s
	@echo ... src/Shape.obj
	@echo ... src/Shape.i
	@echo ... src/Shape.s
	@echo ... src/Speaker.obj
	@echo ... src/Speaker.i
	@echo ... src/Speaker.s
	@echo ... src/SpriteRenderer.obj
	@echo ... src/SpriteRenderer.i
	@echo ... src/SpriteRenderer.s
	@echo ... src/Texture.obj
	@echo ... src/Texture.i
	@echo ... src/Texture.s
	@echo ... src/Transform.obj
	@echo ... src/Transform.i
	@echo ... src/Transform.s
	@echo ... src/UI/Screen.obj
	@echo ... src/UI/Screen.i
	@echo ... src/UI/Screen.s
	@echo ... src/UITexture.obj
	@echo ... src/UITexture.i
	@echo ... src/UITexture.s
	@echo ... src/Utility.obj
	@echo ... src/Utility.i
	@echo ... src/Utility.s
	@echo ... src/WireframeRenderer.obj
	@echo ... src/WireframeRenderer.i
	@echo ... src/WireframeRenderer.s
	@echo ... src/adventure/Bridge.obj
	@echo ... src/adventure/Bridge.i
	@echo ... src/adventure/Bridge.s
	@echo ... src/adventure/Chalise.obj
	@echo ... src/adventure/Chalise.i
	@echo ... src/adventure/Chalise.s
	@echo ... src/adventure/Dragon.obj
	@echo ... src/adventure/Dragon.i
	@echo ... src/adventure/Dragon.s
	@echo ... src/adventure/Game.obj
	@echo ... src/adventure/Game.i
	@echo ... src/adventure/Game.s
	@echo ... src/adventure/GameManager.obj
	@echo ... src/adventure/GameManager.i
	@echo ... src/adventure/GameManager.s
	@echo ... src/adventure/Gate.obj
	@echo ... src/adventure/Gate.i
	@echo ... src/adventure/Gate.s
	@echo ... src/adventure/Item.obj
	@echo ... src/adventure/Item.i
	@echo ... src/adventure/Item.s
	@echo ... src/adventure/Layouts.obj
	@echo ... src/adventure/Layouts.i
	@echo ... src/adventure/Layouts.s
	@echo ... src/adventure/Level.obj
	@echo ... src/adventure/Level.i
	@echo ... src/adventure/Level.s
	@echo ... src/adventure/Magnet.obj
	@echo ... src/adventure/Magnet.i
	@echo ... src/adventure/Magnet.s
	@echo ... src/adventure/Player.obj
	@echo ... src/adventure/Player.i
	@echo ... src/adventure/Player.s
	@echo ... src/adventure/Room.obj
	@echo ... src/adventure/Room.i
	@echo ... src/adventure/Room.s
	@echo ... src/adventure/main.obj
	@echo ... src/adventure/main.i
	@echo ... src/adventure/main.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -P C:\Users\myaka\Documents\Github\Fastboi\CMakeFiles\VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

